# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      registry: safecontainersregistry.azurecr.io
      
    strategy:
      matrix:
        docker-image: [debian, ubuntu, alpine]
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Login to ACR
      - name: Docker Login action
        uses: azure/docker-login@v1
        with:
          login-server: env.registry
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}     
          
      # Run docker build for each image (strategy matrix)
      - name: Run docker build
        run: |
          cd "samples/dotnetapp"
          docker build --pull -t env.registry/dotnetapp:${{ matrix.docker-image }}-${{ github.sha }} -f Dockerfile.${{ matrix.docker-image }}-x64 .
      
